name: xbr
favicon: null
layout_spectrum: 0.18428
typography_spectrum: 0.17537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfbfbf'
    - '#5c5c5c'
    - '#b9b9b9'
    - '#e5e5e5'
    - '#b7b7b7'
  brandStrength: 0.75
  lightness: 0.08638298721052706
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
