name: xbr
favicon: null
layout_spectrum: 0.18428
typography_spectrum: 0.15729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9d3e7'
    - '#feffff'
    - '#26539c'
    - '#4f94bb'
    - '#0e288b'
  brandStrength: 0.20683008036576211
  lightness: 0.08638298721052706
  saturation: 0.4883887500036508
  rhythmicContrast: 0.660509649431333
purpose: []
